// <auto-generated />
using System;
using MailMeBilling.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MailMeBilling.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200626060003_kll")]
    partial class kll
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MailMeBilling.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BranchAddress")
                        .HasColumnType("text");

                    b.Property<string>("Branchname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("branch");
                });

            modelBuilder.Entity("MailMeBilling.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Branddescription")
                        .HasColumnType("text");

                    b.Property<string>("Brandname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("brand");
                });

            modelBuilder.Entity("MailMeBilling.Models.Category", b =>
                {
                    b.Property<int>("categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Categorydiscription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categorys")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("categoryid");

                    b.ToTable("category");
                });

            modelBuilder.Entity("MailMeBilling.Models.Color", b =>
                {
                    b.Property<int>("Colorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Colors")
                        .HasColumnType("text");

                    b.Property<string>("Colorsdscription")
                        .HasColumnType("text");

                    b.HasKey("Colorid");

                    b.ToTable("color");
                });

            modelBuilder.Entity("MailMeBilling.Models.CustomerDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Customername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emailid")
                        .HasColumnType("text");

                    b.Property<string>("Entryby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Entrydate")
                        .HasColumnType("datetime");

                    b.Property<string>("Mobilenumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Points")
                        .HasColumnType("bigint");

                    b.Property<int>("Shopid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("customerdetails");
                });

            modelBuilder.Entity("MailMeBilling.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Userid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("login");
                });

            modelBuilder.Entity("MailMeBilling.Models.Product", b =>
                {
                    b.Property<int>("productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entryby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Entrydate")
                        .HasColumnType("datetime");

                    b.Property<string>("Hsncode")
                        .HasColumnType("text");

                    b.Property<decimal>("Purchaserate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Salesrate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SubcCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("productname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("stock")
                        .HasColumnType("bigint");

                    b.HasKey("productid");

                    b.ToTable("product");
                });

            modelBuilder.Entity("MailMeBilling.Models.Purchaseinvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Billby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Billdate")
                        .HasColumnType("datetime");

                    b.Property<int>("Billno")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Hsncode")
                        .HasColumnType("text");

                    b.Property<string>("Productname")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("purchaseinvoices");
                });

            modelBuilder.Entity("MailMeBilling.Models.Purchaseinvoicesummery", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Billby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Billdate")
                        .HasColumnType("datetime");

                    b.Property<int>("Billid")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Gst")
                        .HasColumnType("text");

                    b.Property<string>("Mobilenumber")
                        .HasColumnType("text");

                    b.Property<string>("Paymenttype")
                        .HasColumnType("text");

                    b.Property<string>("Refcode")
                        .HasColumnType("text");

                    b.Property<decimal>("Totalamount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Totalqty")
                        .HasColumnType("int");

                    b.Property<string>("Vendorrname")
                        .HasColumnType("text");

                    b.Property<string>("ntow")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("purchaseinvoicesummeries");
                });

            modelBuilder.Entity("MailMeBilling.Models.RolleDetails", b =>
                {
                    b.Property<int>("Employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comfirmpassword")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entryby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Entrydate")
                        .HasColumnType("datetime");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobilenumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Roll")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Employeeid");

                    b.ToTable("employeedetails");
                });

            modelBuilder.Entity("MailMeBilling.Models.Salesinvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Billby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Billdate")
                        .HasColumnType("datetime");

                    b.Property<int>("Billno")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Hsncode")
                        .HasColumnType("text");

                    b.Property<string>("Productname")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("salesinvoices");
                });

            modelBuilder.Entity("MailMeBilling.Models.Salesinvoicesummery", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Billby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Billdate")
                        .HasColumnType("datetime");

                    b.Property<int>("Billid")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<int>("Cgst")
                        .HasColumnType("int");

                    b.Property<string>("Customername")
                        .HasColumnType("text");

                    b.Property<int>("Gst")
                        .HasColumnType("int");

                    b.Property<int>("Igst")
                        .HasColumnType("int");

                    b.Property<string>("Mobilenumber")
                        .HasColumnType("text");

                    b.Property<string>("Paymenttype")
                        .HasColumnType("text");

                    b.Property<string>("Refcode")
                        .HasColumnType("text");

                    b.Property<int>("Sgst")
                        .HasColumnType("int");

                    b.Property<decimal>("Totalamount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Totalqty")
                        .HasColumnType("int");

                    b.Property<string>("ntow")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("salesinvoicesummery");
                });

            modelBuilder.Entity("MailMeBilling.Models.SubCategory", b =>
                {
                    b.Property<int>("Subcategoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Subcatagory")
                        .HasColumnType("text");

                    b.Property<string>("Subcatagorydiscription")
                        .HasColumnType("text");

                    b.HasKey("Subcategoryid");

                    b.ToTable("subcategory");
                });

            modelBuilder.Entity("MailMeBilling.Models.Tmppurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Billby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Billdate")
                        .HasColumnType("datetime");

                    b.Property<int>("Billno")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Hsncode")
                        .HasColumnType("text");

                    b.Property<string>("Productname")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tmppurchases");
                });

            modelBuilder.Entity("MailMeBilling.Models.Vendor", b =>
                {
                    b.Property<int>("vendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Accountnumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bankname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Ifsccode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Mobilenumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bankbranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("vendorId");

                    b.ToTable("vendor");
                });

            modelBuilder.Entity("MailMeBilling.Models.tempseccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Billby")
                        .HasColumnType("text");

                    b.Property<DateTime>("Billdate")
                        .HasColumnType("datetime");

                    b.Property<int>("Billno")
                        .HasColumnType("int");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Hsncode")
                        .HasColumnType("text");

                    b.Property<string>("Productname")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tempseccions");
                });
#pragma warning restore 612, 618
        }
    }
}
